//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy_Sell
    {
        public int Id { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
