//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Chats = new HashSet<Chat>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<int> SellerId { get; set; }
    
        public virtual Buyer Buyer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        public virtual Product Product { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
