//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PossibleValue
    {
        public int id { get; set; }
        public string Value { get; set; }
        public Nullable<int> SpecificationId { get; set; }
    
        public virtual Specification Specification { get; set; }
        public virtual Value Value1 { get; set; }
    }
}
