//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demiral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQ()
        {
            this.Attaches = new HashSet<Attach>();
            this.Images = new HashSet<Image>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> BuyerId { get; set; }
        public Nullable<bool> ExtraQoutes { get; set; }
        public Nullable<bool> UrgentRequest { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Description { get; set; }
        public Nullable<int> Pices { get; set; }
        public Nullable<decimal> PreferedUnitPrice { get; set; }
        public Nullable<int> ShippingMethod { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public string DestinationPort { get; set; }
        public Nullable<int> Insurance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attach> Attaches { get; set; }
        public virtual Buyer Buyer { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
